export function generateShareLink(sopId, formData) {
  const payload = { sopId, formData };
  const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(payload))));
  return `${window.location.href.split("#")[0]}#share=${encoded}`;
}

export function decodeShareLink() {
  const hash = window.location.hash;
  if (!hash.startsWith("#share=")) return null;
  try {
    const decoded = decodeURIComponent(escape(atob(hash.slice(7))));
    return JSON.parse(decoded);
  } catch { return null; }
}

function buildSopExportHtml(sop, formData, farmProfile) {
  const esc = (value = "") =>
    String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");

  const getVal = (id) => {
    const v = formData[id];
    if (Array.isArray(v)) return v.join(", ");
    return v || "";
  };
  let html = `<html><head><meta charset="utf-8"><title>${esc(sop.title)} SOP</title><style>
    @page{size:Letter;margin:0.75in 0.8in 0.75in 0.8in;}
    html,body{margin:0;padding:0;}
    body{font-family:Calibri,sans-serif;font-size:11pt;color:#1f2937;text-align:left;}
    .doc{width:100%;max-width:6.9in;margin:0;box-sizing:border-box;}
    h1{font-size:16pt;color:#0b3a74;border-bottom:2px solid #0b3a74;padding-bottom:6pt;margin:0 0 8pt 0;}
    h2{font-size:13pt;color:#124e96;margin:18pt 0 8pt 0;}
    h3{font-size:11pt;color:#334155;margin-top:12pt;}
    .field{margin-bottom:10pt;} .label{font-weight:bold;color:#374151;}
    .value{border-bottom:1px solid #cbd5e1;min-width:200pt;display:inline-block;min-height:14pt;}
    p,span,td,th,div{word-break:break-word;overflow-wrap:anywhere;}
    table{width:100%;border-collapse:collapse;margin-top:10pt;font-size:9pt;table-layout:fixed;}
    th{background:#0b3a74;color:white;padding:6pt;text-align:left;}
    td{border:1px solid #cbd5e1;padding:5pt;vertical-align:top;}
    tr:nth-child(even){background:#eff6ff;}
    .header-block{background:#eff6ff;padding:12pt;border:1px solid #bfdbfe;margin-bottom:18pt;}
    thead{display:table-header-group;}
    tr{page-break-inside:avoid;}
  </style></head><body>`;
  html += `<div class="doc"><div class="header-block">`;
  if (farmProfile?.farm_name) html += `<h1>${esc(farmProfile.farm_name)}</h1>`;
  html += `<h1>${esc(sop.title)}</h1>`;
  html += `<p><strong>Reference:</strong> ${esc(sop.ref)}</p>`;
  if (farmProfile) {
    html += `<p><strong>Farm:</strong> ${esc(farmProfile.farm_name || "")} | <strong>Address:</strong> ${esc(farmProfile.address || "")}</p>`;
    html += `<p><strong>Operation Type:</strong> ${esc(farmProfile.operation_type || "")} | <strong>Certifier:</strong> ${esc(farmProfile.certifier || "")}</p>`;
  }
  html += `</div>`;
  for (const section of sop.sections) {
    html += `<h2>${esc(section.title)}</h2>`;
    for (const field of section.fields) {
      const val = getVal(field.id);
      html += `<div class="field"><span class="label">${esc(field.label)}: </span>`;
      html += val ? `<span>${esc(val).replace(/\n/g, "<br/>")}</span>` : `<span class="value">&nbsp;</span>`;
      html += `</div>`;
    }
  }
  html += `<h2>${esc(sop.log.title)}</h2>`;
  html += `<table><thead><tr>${sop.log.cols.map(c => `<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>`;
  for (let i = 0; i < 10; i++) html += `<tr>${sop.log.cols.map(() => `<td>&nbsp;</td>`).join("")}</tr>`;
  html += `</tbody></table>`;
  html += `<br/><p style="font-size:9pt;color:#9ca3af;">Generated by Farm Food Safety SOP System | ${new Date().toLocaleDateString()} | FSMA Produce Safety Rule compliant template</p>`;
  html += `</div></body></html>`;
  return html;
}

export function downloadAsDocx(sop, formData, farmProfile) {
  const html = buildSopExportHtml(sop, formData, farmProfile);
  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${sop.title.replace(/[^a-z0-9]/gi, "_")}_SOP.doc`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function printAsPdf(sop, formData, farmProfile) {
  const html = buildSopExportHtml(sop, formData, farmProfile);
  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  iframe.style.visibility = "hidden";
  document.body.appendChild(iframe);

  const cleanup = () => {
    setTimeout(() => {
      if (iframe.parentNode) iframe.parentNode.removeChild(iframe);
    }, 1000);
  };

  iframe.onload = () => {
    try {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
      cleanup();
    } catch {
      cleanup();
      // Final fallback: open export in current tab if iframe print is unavailable.
      const blob = new Blob([html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      window.location.href = url;
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    }
  };

  iframe.srcdoc = html;
}

export function downloadRecordAsDocx(sop, record, farmProfile) {
  const esc = (value = "") =>
    String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");

  const statusLabel = {
    pending: "Pending",
    done: "Completed",
    "not-applicable": "Not Applicable",
    "needs-action": "Needs Corrective Action",
  };

  let html = `<html><head><meta charset="utf-8"><title>${esc(sop.title)} Record</title><style>
    @page{size:Letter;margin:0.7in 0.8in 0.7in 0.8in;}
    html,body{margin:0;padding:0;}
    body{font-family:Calibri,sans-serif;font-size:11pt;color:#1f2937;}
    .doc{max-width:6.9in;}
    h1{font-size:16pt;color:#0b3a74;border-bottom:2px solid #0b3a74;padding-bottom:6pt;margin:0 0 8pt 0;}
    h2{font-size:13pt;color:#124e96;margin:18pt 0 8pt 0;}
    .meta{background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:10pt;margin-bottom:12pt;}
    .meta-row{margin:4pt 0;}
    table{width:100%;border-collapse:collapse;font-size:9pt;table-layout:fixed;}
    th{background:#0b3a74;color:white;padding:6pt;text-align:left;vertical-align:top;}
    td{border:1px solid #cbd5e1;padding:5pt;vertical-align:top;word-break:break-word;overflow-wrap:anywhere;}
    tr:nth-child(even){background:#eff6ff;}
    thead{display:table-header-group;}
    tr{page-break-inside:avoid;}
  </style></head><body><div class="doc">`;

  html += `<h1>${esc(record.sopTitle || sop.title)} — Activity Record</h1>`;
  html += `<div class="meta">`;
  html += `<div class="meta-row"><strong>Reference:</strong> ${esc(sop.ref)}</div>`;
  html += `<div class="meta-row"><strong>Farm:</strong> ${esc(record.farmName || farmProfile?.farm_name || "")}</div>`;
  html += `<div class="meta-row"><strong>Activity Date:</strong> ${esc(record.activityDate || "")}</div>`;
  html += `<div class="meta-row"><strong>Performed By:</strong> ${esc(record.performedBy || "")}</div>`;
  html += `<div class="meta-row"><strong>Verified By:</strong> ${esc(record.verifiedBy || "")}</div>`;
  html += `<div class="meta-row"><strong>Record Notes:</strong> ${esc(record.notes || "")}</div>`;
  html += `</div>`;

  html += `<h2>Checklist Cross-Check</h2>`;
  html += `<table><thead><tr>`;
  ["Section", "Checklist Item", "Expected SOP Requirement", "Status", "Evidence / Notes"].forEach((col) => {
    html += `<th>${esc(col)}</th>`;
  });
  html += `</tr></thead><tbody>`;

  (record.items || []).forEach((item) => {
    html += `<tr>`;
    html += `<td>${esc(item.sectionTitle || "")}</td>`;
    html += `<td>${esc(item.label || "")}</td>`;
    html += `<td>${esc(item.expected || "")}</td>`;
    html += `<td>${esc(statusLabel[item.status] || item.status || "Pending")}</td>`;
    html += `<td>${esc(item.notes || "")}</td>`;
    html += `</tr>`;
  });
  html += `</tbody></table>`;
  html += `<p style="font-size:9pt;color:#9ca3af;margin-top:12pt;">Generated by Farm Food Safety SOP System | ${new Date().toLocaleDateString()}</p>`;
  html += `</div></body></html>`;

  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${(record.sopTitle || sop.title).replace(/[^a-z0-9]/gi, "_")}_Record.doc`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
